name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install PostgreSQL development tools
      run: sudo apt install postgresql postgresql-server-dev-14

    - name: Make
      run: make

    - name: Install
      run: sudo make install

    - name: Setup PostgreSQL
      run: sudo -u postgres /usr/lib/postgresql/14/bin/postgres --config-file=/etc/postgresql/14/main/postgresql.conf &

    - name: Test extension
      run: sudo -u postgres bash contrib/testcase.sh
