name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install PostgreSQL development tools
      run: sudo apt install postgresql-server-dev
    - name: Make
      run: make
    # - name: Install
    #   run: sudo make install
